wayland: Support HiDPI for cursor
emersion/mako pull request #406
Opened 2022-01-17 06:24 UTC by Nefsen402

2022-01-17 10:23 UTC, Nefsen402 commented
!393 Seems to do the same thing, plus some extra.

2022-01-20 07:40 UTC, emersion requested changes
Thanks for the patch! Here are some minor comments. The meat of the patch looks good.

2022-01-20 07:40 UTC, emersion commented on wayland.c
> +	if (state->cursor.theme != NULL && state->cursor.scale == scale)
Style: braces are mandatory. Applies to the whole patch.

2022-01-20 07:40 UTC, emersion commented on wayland.c
> +void load_cursor(struct mako_state *state, uint32_t scale) {
Nit: this function can be `static`.

2022-01-20 07:40 UTC, emersion commented on wayland.c
> +		if (surface->surface_output->scale > scale) scale = surface->surface_output->scale;
Style: braces are mandatory

2022-01-20 07:54 UTC, emersion approved these changes
Thanks!

2022-01-20 07:54 UTC, merged